import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import AuthProvider from "./_Context/Authentication";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${poppins.variable} font-sans`}
      >
        <AuthProvider>
          <Provider>{children}</Provider>
        </AuthProvider>

      </body>
    </html>
  );
}
